#ifndef LAYOUT_HPP_INCLUDED
#define LAYOUT_HPP_INCLUDED

/********************************************************************/
/**                            LAYOUT                              **/
/********************************************************************/
#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 360

#define TAB_POSX                10
#define TAB_POSY                30
#define TAB_WIDTH               600
#define TAB_HEIGHT              220

#define COLOR_CLASSIC_NORMAL_BTN_TOP RGB(100, 100, 100)
#define COLOR_CLASSIC_NORMAL_BTN_BTM RGB(60, 60, 60)
#define COLOR_CLASSIC_NORMAL_FRAME_BTN RGB(255, 170, 0)
#define COLOR_CLASSIC_TXT_NORMAL_BTN RGB(255, 190, 0)

#define COLOR_CLASSIC_PUSHED_BTN_TOP RGB(50, 50, 50)
#define COLOR_CLASSIC_PUSHED_BTN_BTM RGB(80, 80, 80)
#define COLOR_CLASSIC_PUSHED_FRAME_BTN RGB(230, 140, 0)
#define COLOR_CLASSIC_TXT_PUSHED_BTN RGB(210, 160, 0)

#define COLOR_CLASSIC_DISABLED_BTN_TOP RGB(70, 70, 70)
#define COLOR_CLASSIC_DISABLED_BTN_BTM RGB(70, 70, 70)
#define COLOR_CLASSIC_DISABLED_FRAME_BTN RGB(200, 110, 0)
#define COLOR_CLASSIC_TXT_DISABLED_BTN RGB(170, 170, 170)

/*  SIMULATE SEQ BUTTON     */
#define BTN_SIMULATE_SEQ_WIDTH      80
#define BTN_SIMULATE_SEQ_HEIGHT     30
#define BTN_SIMULATE_SEQ_POSX       (TAB_WIDTH/2+35)
#define BTN_SIMULATE_SEQ_POSY       20

#define COLOR_TXT_BTN_START_SEQ_RELEASED    RGB(0, 230, 70)
#define COLOR_TXT_BTN_START_SEQ_PUSHED      RGB(0, 150, 30)
#define COLOR_TXT_BTN_START_SEQ_DISABLED    RGB(150, 150, 150)

/*  START SEQ BUTTTON   */
#define BTN_START_SEQ_WIDTH     180
#define BTN_START_SEQ_HEIGHT    40
#define BTN_START_SEQ_POSX      (BTN_SIMULATE_SEQ_POSX+BTN_SIMULATE_SEQ_WIDTH+10)
#define BTN_START_SEQ_POSY      (BTN_SIMULATE_SEQ_POSY+(BTN_SIMULATE_SEQ_HEIGHT/2-BTN_START_SEQ_HEIGHT/2))

#define PBBAR_POSX              TAB_POSX
#define PBBAR_POSY              (TAB_POSX+TAB_HEIGHT+30)
#define PBBAR_WIDTH             TAB_WIDTH
#define PBBAR_HEIGHT            10

#define SB_UPDOWN_WIDTH         20//    standard pour tout les UpDown
#define SB_UPDOWN_HEIGHT        40

/****************  ONGLET CRÉER  ***************/
#define BTN_CREATE_SEQ_POSX         (TAB_POSX+10)
#define BTN_CREATE_SEQ_POSY         (TAB_POSY+40)
#define BTN_CREATE_SEQ_WIDTH        200
#define BTN_CREATE_SEQ_HEIGHT       30

#define TEXT_CREATION_SEQ_POSX      (TAB_POSX+10)
#define TEXT_CREATION_SEQ_POSY      (TAB_POSY+BTN_NEW_ACTION_HEIGHT+45)
#define TEXT_CREATION_SEQ_WIDTH     (TAB_WIDTH-20)
#define TEXT_CREATION_SEQ_HEIGHT    (40)

#define LISTBOX_KEY_POSX            (TAB_POSX+10)
#define LISTBOX_KEY_POSY            (TAB_POSY+BTN_CREATE_SEQ_HEIGHT+TEXT_CREATION_SEQ_HEIGHT+50)
#define LISTBOX_KEY_WIDTH           (TAB_WIDTH-100)
#define LISTBOX_KEY_HEIGHT          110

/****************  ONGLET CHARGER   ***************/
#define BTN_LOAD_FILE_POSX          (TAB_POSX+20)
#define BTN_LOAD_FILE_POSY          (TAB_POSY+50)
#define BTN_LOAD_FILE_WIDTH         125
#define BTN_LOAD_FILE_HEIGHT        55

#define BTN_SAVE_FILE_POSX          (TAB_POSX+20)
#define BTN_SAVE_FILE_POSY          (TAB_POSY+BTN_LOAD_FILE_HEIGHT+60)
#define BTN_SAVE_FILE_WIDTH         125
#define BTN_SAVE_FILE_HEIGHT        55

#define BTN_DELETE_FILE_WIDTH       100
#define BTN_DELETE_FILE_HEIGHT      30
#define BTN_DELETE_FILE_POSX        (BTN_LOAD_FILE_POSX+(BTN_LOAD_FILE_WIDTH/2-BTN_DELETE_FILE_WIDTH/2))
#define BTN_DELETE_FILE_POSY        (TAB_POSY+BTN_LOAD_FILE_HEIGHT+BTN_SAVE_FILE_HEIGHT+70)
#define BTN_DELETE_FILE_ICO_WIDTH   25
#define BTN_DELETE_FILE_ICO_HEIGHT  25

#define LISTBOX_FILES_POSX          (TAB_POSX+220)
#define LISTBOX_FILES_POSY          BTN_LOAD_FILE_POSY
#define LISTBOX_FILES_WIDTH         (TAB_WIDTH-240)
#define LISTBOX_FILES_HEIGHT        (TAB_HEIGHT-50)

/****************  ONGLET MODIFIER  ***************/
#define LISTBOX_ACTIONS_POSX        (TAB_POSX+20)
#define LISTBOX_ACTIONS_POSY        (TAB_POSY+50)
#define LISTBOX_ACTIONS_WIDTH       (TAB_WIDTH-240)
#define LISTBOX_ACTIONS_HEIGHT      (TAB_HEIGHT-50)

#define BTN_NEW_ACTION_POSX         (TAB_WIDTH-200)
#define BTN_NEW_ACTION_POSY         LISTBOX_ACTIONS_POSY
#define BTN_NEW_ACTION_WIDTH        150
#define BTN_NEW_ACTION_HEIGHT       30

#define BTN_DELETE_ACTION_POSX      (BTN_NEW_ACTION_POSX+BTN_NEW_ACTION_WIDTH+10)
#define BTN_DELETE_ACTION_POSY      LISTBOX_ACTIONS_POSY
#define BTN_DELETE_ACTION_WIDTH     40
#define BTN_DELETE_ACTION_HEIGHT    30

#define SB_ACTIONX_POSX             (BTN_NEW_ACTION_POSX)
#define SB_ACTIONX_POSY             (LISTBOX_ACTIONS_POSY+40)
#define SB_ACTIONX_WIDTH            75
#define SB_ACTIONX_HEIGHT           25

#define SB_ACTIONY_POSX             (BTN_NEW_ACTION_POSX+SB_ACTIONX_WIDTH+SB_UPDOWN_WIDTH+10)
#define SB_ACTIONY_POSY             (SB_ACTIONX_POSY)
#define SB_ACTIONY_WIDTH            75
#define SB_ACTIONY_HEIGHT           25

#define EDIT_TIME_POSX                (BTN_NEW_ACTION_POSX)
#define EDIT_TIME_POSY                (LISTBOX_ACTIONS_POSY+SB_ACTIONX_HEIGHT+60)
#define EDIT_TIME_WIDTH               180
#define EDIT_TIME_HEIGHT              25

#define CB_COMMAND_POSX             (BTN_NEW_ACTION_POSX)
#define CB_COMMAND_POSY             (LISTBOX_ACTIONS_POSY+BTN_CREATE_SEQ_HEIGHT+SB_ACTIONX_HEIGHT+SB_ACTIONY_HEIGHT+45)
#define CB_COMMAND_WIDTH            200
#define CB_COMMAND_HEIGHT           40

/****************  ONGLET OPTIONS  ***************/
#define TEXT_EDIT_KEY_POSX      (TAB_POSX+10)
#define TEXT_EDIT_KEY_POSY      (TAB_POSY+40)
#define TEXT_EDIT_KEY_WIDTH     TAB_WIDTH-20
#define TEXT_EDIT_KEY_HEIGHT    20

#define CB_COMMAND_KEY_POSX     (TAB_POSX+10)
#define CB_COMMAND_KEY_POSY     (TEXT_EDIT_KEY_POSY+50)
#define CB_COMMAND_KEY_WIDTH    250
#define CB_COMMAND_KEY_HEIGHT   25

#define BTN_EDIT_KEY_WIDTH      120
#define BTN_EDIT_KEY_HEIGHT     55
#define BTN_EDIT_KEY_POSX       (TAB_POSX+CB_COMMAND_KEY_WIDTH+20)
#define BTN_EDIT_KEY_POSY       (CB_COMMAND_KEY_POSY+(CB_COMMAND_KEY_HEIGHT/2-BTN_EDIT_KEY_HEIGHT/2))//

#endif // LAYOUT_HPP_INCLUDED
